export const data = [
    {
      "cloudServiceProvider": "AWS",
      "agency": "Department of IT",
      "tenantName": "acme-corp",
      "accountName": "ACME Cloud Services",
      "accountNumber": "123456789",
      "compliantCheckCounts": 150,
      "nonCompliantCheckCounts": 20,
      "suppressedChecksCounts": 5,
      "appCodeFullName": "ABC123 - My Application",
      "environment": "Production",
      "goLiveDate": "2023-01-15",
      "createdDate": "2023-01-01T08:00:00Z",
      "createdBy": "John Doe",
      "updatedDate": "2023-05-15T14:30:00Z",
      "updatedBy": "Jane Smith"
    },
    {
      "cloudServiceProvider": "Azure",
      "agency": "Department of Finance",
      "tenantName": "xyz-inc",
      "accountName": "XYZ Cloud Services",
      "accountNumber": "987654321",
      "compliantCheckCounts": 120,
      "nonCompliantCheckCounts": 30,
      "suppressedChecksCounts": 10,
      "appCodeFullName": "XYZ456 - Finance App",
      "environment": "Testing",
      "goLiveDate": "2023-02-28",
      "createdDate": "2023-02-01T10:45:00Z",
      "createdBy": "Alice Johnson",
      "updatedDate": "2023-09-20T16:20:00Z",
      "updatedBy": "Bob Johnson"
    },
    {
        "cloudServiceProvider": "Google Cloud",
        "agency": "Department of Operations",
        "tenantName": "omega-tech",
        "accountName": "Omega Tech Cloud",
        "accountNumber": "345678901",
        "compliantCheckCounts": 180,
        "nonCompliantCheckCounts": 15,
        "suppressedChecksCounts": 8,
        "appCodeFullName": "OPQ789 - Operations System",
        "environment": "Staging",
        "goLiveDate": "2023-04-30",
        "createdDate": "2023-03-01T09:30:00Z",
        "createdBy": "Charlie Brown",
        "updatedDate": "2023-11-10T12:15:00Z",
        "updatedBy": "David Johnson"
      },
      {
        "cloudServiceProvider": "IBM Cloud",
        "agency": "Department of HR",
        "tenantName": "hr-solutions",
        "accountName": "HR Solutions Cloud",
        "accountNumber": "567890123",
        "compliantCheckCounts": 160,
        "nonCompliantCheckCounts": 25,
        "suppressedChecksCounts": 12,
        "appCodeFullName": "LMN012 - HR Management",
        "environment": "Development",
        "goLiveDate": "2023-07-15",
        "createdDate": "2023-05-01T14:00:00Z",
        "createdBy": "Eva Smith",
        "updatedDate": "2023-09-25T18:45:00Z",
        "updatedBy": "Frank White"
      },
      {
        "cloudServiceProvider": "Oracle Cloud",
        "agency": "Department of Marketing",
        "tenantName": "marketing-co",
        "accountName": "Marketing Cloud",
        "accountNumber": "789012345",
        "compliantCheckCounts": 140,
        "nonCompliantCheckCounts": 35,
        "suppressedChecksCounts": 15,
        "appCodeFullName": "RST345 - Marketing Platform",
        "environment": "Production",
        "goLiveDate": "2023-10-31",
        "createdDate": "2023-08-01T11:30:00Z",
        "createdBy": "Grace Brown",
        "updatedDate": "2023-11-28T16:30:00Z",
        "updatedBy": "Harry Green"
      },
      {
        "cloudServiceProvider": "Alibaba Cloud",
        "agency": "Department of Security",
        "tenantName": "secure-solutions",
        "accountName": "Secure Solutions Cloud",
        "accountNumber": "890123456",
        "compliantCheckCounts": 200,
        "nonCompliantCheckCounts": 10,
        "suppressedChecksCounts": 7,
        "appCodeFullName": "XYZ789 - Security App",
        "environment": "Testing",
        "goLiveDate": "2023-12-15",
        "createdDate": "2023-10-01T08:45:00Z",
        "createdBy": "Ivy Taylor",
        "updatedDate": "2023-12-20T14:15:00Z",
        "updatedBy": "Jackie King"
      },
      {
        "cloudServiceProvider": "Red Hat OpenShift",
        "agency": "Department of Compliance",
        "tenantName": "compliance-central",
        "accountName": "Compliance Central Cloud",
        "accountNumber": "901234567",
        "compliantCheckCounts": 170,
        "nonCompliantCheckCounts": 18,
        "suppressedChecksCounts": 9,
        "appCodeFullName": "ABC123 - Compliance App",
        "environment": "Production",
        "goLiveDate": "2024-01-31",
        "createdDate": "2023-11-01T10:30:00Z",
        "createdBy": "Kevin Miller",
        "updatedDate": "2023-12-22T16:00:00Z",
        "updatedBy": "Linda Moore"
      },
      {
        "cloudServiceProvider": "VMware Cloud",
        "agency": "Department of Logistics",
        "tenantName": "logistics-cloud",
        "accountName": "Logistics Cloud",
        "accountNumber": "1234567890",
        "compliantCheckCounts": 190,
        "nonCompliantCheckCounts": 12,
        "suppressedChecksCounts": 6,
        "appCodeFullName": "PQR789 - Logistics App",
        "environment": "Staging",
        "goLiveDate": "2024-03-30",
        "createdDate": "2024-02-01T08:30:00Z",
        "createdBy": "Mike Davis",
        "updatedDate": "2024-04-15T14:00:00Z",
        "updatedBy": "Nancy White"
      },
      {
        "cloudServiceProvider": "Cisco Cloud",
        "agency": "Department of Networking",
        "tenantName": "network-solutions",
        "accountName": "Network Solutions Cloud",
        "accountNumber": "2345678901",
        "compliantCheckCounts": 180,
        "nonCompliantCheckCounts": 15,
        "suppressedChecksCounts": 8,
        "appCodeFullName": "OPQ789 - Networking App",
        "environment": "Development",
        "goLiveDate": "2024-05-15",
        "createdDate": "2024-04-01T09:30:00Z",
        "createdBy": "Charlie Brown",
        "updatedDate": "2024-11-10T12:15:00Z",
        "updatedBy": "David Johnson"
      },
      {
        "cloudServiceProvider": "HP Helion",
        "agency": "Department of Support",
        "tenantName": "support-cloud",
        "accountName": "Support Cloud",
        "accountNumber": "3456789012",
        "compliantCheckCounts": 160,
        "nonCompliantCheckCounts": 20,
        "suppressedChecksCounts": 10,
        "appCodeFullName": "LMN012 - Support App",
        "environment": "Production",
        "goLiveDate": "2024-07-30",
        "createdDate": "2024-06-01T14:00:00Z",
        "createdBy": "Eva Smith",
        "updatedDate": "2024-09-25T18:45:00Z",
        "updatedBy": "Frank White"
      },
      {
        "cloudServiceProvider": "Dell Cloud",
        "agency": "Department of Analytics",
        "tenantName": "analytics-central",
        "accountName": "Analytics Central Cloud",
        "accountNumber": "4567890123",
        "compliantCheckCounts": 140,
        "nonCompliantCheckCounts": 25,
        "suppressedChecksCounts": 12,
        "appCodeFullName": "RST345 - Analytics Platform",
        "environment": "Testing",
        "goLiveDate": "2024-10-31",
        "createdDate": "2024-08-01T11:30:00Z",
        "createdBy": "Grace Brown",
        "updatedDate": "2024-11-28T16:30:00Z",
        "updatedBy": "Harry Green"
      },
  ]
  ;